server:
  port: 8080
spring:
  application:
    name: gateway
    gateway:
      routes:
      # ================= FlashcardService
      - id: flashcard
        uri: lb://flashcard
        predicates:
        - Path=/flashcard/**
      # ================= QuizService
      - id: quiz
        uri: lb://quiz
        predicates:
        - Path=/quiz/**
      # ================= AccountService
      - id: account
        uri: lb://account
        predicates:
        - Path=/account/**
      
  main:
    web-application-type: reactive
